services:
  mysql:
    image: mysql:8.0
    container_name: mysql_rick_and_morty
    restart: always
    environment:
      MYSQL_DATABASE: rick_and_morty
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3303:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
